import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./Provider";
import RecoilRoot from "./RecoilRoot";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "instragram | home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <RecoilRoot>{children}</RecoilRoot>
        </NextAuthProvider>
      </body>
    </html>
  );
}
